services:

  demucs:
    build:
      context: .
      dockerfile: Dockerfile.A
    container_name: demucs_container
    ports:
      - "5000:5000"
    volumes:
      - shared_data:/data

  whisperx:
    build:
      context: .
      dockerfile: Dockerfile.B
    container_name: whisperx_container
    # IMPORTANTE: para GPU
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    ports:
      - "5001:5001"
    volumes:
      - shared_data:/data

volumes:
  shared_data:
    driver: local